config/routes.rb
EsmRails::Application.routes.draw do
  
  resources :directories

  resources :posts do
    collection do
      put :update_attribute_on_the_spot
    end
  end

  devise_for :admins

  root :to => "projects#index"

  devise_for :users, :controllers => {sessions: "sessions"}
  resources :users, :only => :show

  resources :users do
    resources :projects
  end

  resources :projects do
    resources :surveys do
      resources :survey_schedules, :only => :index
    end
    get 'mine', :on => :collection
  end
  
  resources :surveys do
    resources :questions
  end
  
  resources :questions do
    resources :examples
  end
  
  resources :examples
  
  resources :answers

  resources :take_surveys do
    member do
      put 'event'
    end
  end
  
  resources :join_projects do
    member do
      put 'event'
    end
  end
  
  resources :user_histories do
    get 'mine', :on => :collection
  end

  resources :device_tokens, :only => [:create, :destroy]
  
  match 'survey_reports/:id' => 'survey_report#show'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :trackable, :timeoutable, :lockable
  attr_accessible :email, :password, :password_confirmation
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :take_survey
  
  validates_uniqueness_of :take_survey_id, :scope => :question_id
end

app/models/device_token.rb
class DeviceToken < ActiveRecord::Base
  belongs_to :user
  
  validates_uniqueness_of :user_id, :scope => :token
end

app/models/directory.rb
class Directory < ActiveRecord::Base
  has_ancestry
end

app/models/example.rb
class Example < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
end

app/models/join_project.rb
class JoinProject < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  
  validates_uniqueness_of :user_id, :scope => :project_id
  
  include Workflow
  workflow do
    state :requested do
      event :cancel, :transitions_to => :canceled
      event :review, :transitions_to => :in_review
      event :accept, :transitions_to => :accepted
    end
    state :canceled do
      event :request, :transitions_to => :requested
    end
    state :in_review do
      event :accept, :transitions_to => :accepted
      event :reject, :transitions_to => :rejected
    end    
    state :accepted do
      event :reject, :transitions_to => :rejected
      event :abandon, :transitions_to => :abandoned
      event :finish, :transitions_to => :finished
      event :reset_schedule, :transitions_to => :accepted
    end
    state :rejected do
      event :accept, :transitions_to => :accepted
    end
    
    state :abandoned
    state :finished
  end
end

app/models/pns_log.rb
class PnsLog < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  belongs_to :survey
end

app/models/pns_rule.rb
class PnsRule < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :surveys
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :survey
  belongs_to :user
  has_many :examples
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  has_many :questions,:order => 'display_no ASC'
end

app/models/survey_schedule.rb
class SurveySchedule < ActiveRecord::Base
  belongs_to :user
  belongs_to :survey
end

app/models/take_survey.rb
class TakeSurvey < ActiveRecord::Base
  belongs_to :user
  belongs_to :survey
  belongs_to :survey_schedule
  
  # validates_uniqueness_of :user_id, :scope => :survey_id
  
  include Workflow
  workflow do
    state :before_taking do
      event :take, :transitions_to => :on_taking
    end
    state :on_taking do
      event :finish, :transitions_to => :done
      event :timeout, :transitions_to => :not_finish
    end
    state :complete
    state :incomplete
    state :not_finish
  end  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  before_save :ensure_authentication_token
    
  # Include default devise modules. Others available are:
  # :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :token_authenticatable

  # Setup accessible (or protected) attributes for your model
  # attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :authentication_token

  def ensure_authentication_token!   
     reset_authentication_token! if authentication_token.blank?   
  end
  
  def serializable_hash(options = {})
    # options[:except] ||= [:confirmation_token, :encrypted_password, :token_authenticatable]
    options[:only] ||= [:email, :name, :id, :created_at, :updated_at, :authentication_token]
    super(options)
  end
end

app/models/user_history.rb
class UserHistory < ActiveRecord::Base
  belongs_to :user
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  prepend_before_filter :get_api_key
  before_filter :authenticate_user!
  
  private
  def get_api_key
    if api_key = params[:api_key].blank? && request.headers["X-API-KEY"]
      params[:api_key] = api_key
    end
  end

  public
  def create    
    ActiveRecord::Base.transaction do
      @result = true
      @answers = ActiveSupport::JSON.decode(params[:answers])

      survey_schedule_id = params[:survey_schedule_id]
      
      if survey_schedule_id
        @aSchedule = SurveySchedule.find(survey_schedule_id)
        if !@answers.last[:take_survey_id]
          @take_survey = TakeSurvey.new()
          @take_survey.survey_id = @aSchedule.survey_id
          @take_survey.survey_schedule_id = @aSchedule.id
          @take_survey.user = current_user
          @take_survey.workflow_state = :complete
          @take_survey.save
        end
      end
      
      
      @answers.each do |answer|
        @answer = Answer.create(answer)
        @answer.take_survey_id = @take_survey.id if !@answer.take_survey_id && @take_survey
        
        if @answer.save
          @result = true
        else
          @result = false
          break
        end
      end
    end

    if @result and @aSchedule
      @aSchedule.attend = true;
      @aSchedule.save;
    end
    
    respond_to do |format|
      format.json { render json: {:result => @result}, status: :unprocessable_entity }
    end
        
  end
  
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <%= f.hidden_field :survey_id, :value => @survey.id %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>질문을 수정함</h1>

<%= render 'form' %>

<%= link_to 'Show', survey_question_path(@survey, @question) %> |
<%= link_to 'Back', survey_questions_path(@survey) %>

app/views/answers/index.html.erb
<h3><%=link_to @survey.title, @survey%>설문지에 포함된 질문들</h3>

	<% if @questions.empty? %>
	  <p> 질문이 없어요. <%=link_to '추가할까요?', new_survey_question_path(@survey) %> </p>
	<% else %>
		<% @questions.each do |question| %>
		  <%=link_to question.title, survey_question_path(@survey, question) %> <br />
		<% end %>
		
		<br />
		<%= link_to '새 질문', new_survey_question_path(@survey) %>
	<% end %>

app/views/answers/new.html.erb
<h1>새 질문</h1>

<%= render 'form' %>

<%= link_to 'Back', survey_questions_path(@survey) %>

app/views/answers/show.html.erb
<h1>질문</h1>
<p>질문 명: <%= @question.title %></p>
<p>질문 부연 설명: <%= @question.description if @question.description %></p>
	

<% if user_signed_in? and current_user == @question.user %>
<%= link_to 'Edit', edit_survey_question_path(@survey, @question) %> |
<%= link_to 'Destroy', @question, confirm: 'Are you sure?', method: :delete %> |
<% end %>
<%= link_to 'Back', survey_questions_path(@survey) %> 