config/routes.rb
EsmRails::Application.routes.draw do
  
  resources :directories

  resources :posts do
    collection do
      put :update_attribute_on_the_spot
    end
  end

  devise_for :admins

  root :to => "projects#index"

  devise_for :users, :controllers => {sessions: "sessions"}
  resources :users, :only => :show

  resources :users do
    resources :projects
  end

  resources :projects do
    resources :surveys do
      resources :survey_schedules, :only => :index
    end
    get 'mine', :on => :collection
  end
  
  resources :surveys do
    resources :questions
  end
  
  resources :questions do
    resources :examples
  end
  
  resources :examples
  
  resources :answers

  resources :take_surveys do
    member do
      put 'event'
    end
  end
  
  resources :join_projects do
    member do
      put 'event'
    end
  end
  
  resources :user_histories do
    get 'mine', :on => :collection
  end

  resources :device_tokens, :only => [:create, :destroy]
  
  match 'survey_reports/:id' => 'survey_report#show'

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :surveys
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  prepend_before_filter :get_api_key
  before_filter :authenticate_user!, :except => [:index]
  
  private
  def get_api_key
    if api_key = params[:api_key].blank? && request.headers["X-API-KEY"]
      params[:api_key] = api_key
    end
  end
  
  public
  def index
    
    case params[:section_name]
    when 'featured'
      @projects = Project.where("start_date > ?", Date.today)
    when 'latest'
      @projects = Project.where("start_date > ?", Date.today).order('projects.created_at desc').limit(20)
    when 'popular'
      @projects = Project.where("start_date > ?", Date.today)
    else
      @projects = Project.all
    end
          
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects.to_json(:include => {:user => {:only => [:name, :email]} }) }
      # format.json { render json: @survey.to_json(:include => {:questions => 
      #   {:only => [:id, :title], :include => {:examples => {:only => [:id, :title]}}}}) }
    end
  end
  
  # my projects
  def mine
    # @projects = JoinProject.find(:all, :include => :project)

    case params[:status_filter]
    when 'in_review'
      @projects = JoinProject.where("user_id = ? AND workflow_state IN ('requested', 'in_review')", current_user).order("updated_at").reverse_order
    when 'accepted'
      @projects = JoinProject.where("user_id = ? AND workflow_state = 'accepted'", current_user).order("updated_at").reverse_order
    when 'finished'
      @projects = JoinProject.where("user_id = ? AND workflow_state = 'finished'", current_user).order("updated_at").reverse_order
    end
    
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects.to_json(:include => :project) }
      # format.json { render json: @survey.to_json(:include => {:questions => 
      #   {:only => [:id, :title], :include => {:examples => {:only => [:id, :title]}}}}) }
    end
    
  end
  
  
  def show

    begin
      @project = Project.find(params[:id])
      
    rescue ActiveRecord::RecordNotFound
      render json: {:error => "Project Not Found"}
      return
    end

    @surveys = @project.surveys
    @join_projects = JoinProject.where(:project_id => params[:id], :user_id => current_user.id)
    @members = JoinProject.where(:project_id => params[:id])
    

    respond_to do |format|
      format.html # new.html.erb
      format.json do
        if @join_projects.any?
          render json: {:project => @project, :user => @project.user.as_json(:only => [:name, :email]),
          :join_project => @join_projects.first}
        else
          render json: {:project => @project, :user => @project.user.as_json(:only => [:name, :email]) }
        end  
      end
    end
  end
  
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end
  
  def create
    @project = Project.new(params[:project])
    @project.user = current_user

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def edit
    @project = Project.find(params[:id])
  end
  
  def update
    @project = Project.find(params[:id])
    @project.user = current_user

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    
    @project = Project.find(params[:id])
    print current_user, @project.user
    if user_signed_in? and current_user == @project.user
      @project.destroy

      respond_to do |format|
        format.html { redirect_to projects_url }
        format.json { head :ok }
      end
    else
      respond_to do |format|
        format.html { head :forbidden }
        format.json { head :forbidden }
      end
    end
  end
  
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :start_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :start_date, :class => 'date_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :end_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :end_date, :class => 'date_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :max_attends_number, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :max_attends_number, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :point, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :point, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                projects_path, :class => 'btn' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<%- model_class = @project.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/projects/index.html.erb
<%- model_class = Project.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:owner) %></th>
      <th><%= model_class.human_attribute_name(:start_date) %></th>
      <th><%= model_class.human_attribute_name(:end_date) %></th>
      <th><%= model_class.human_attribute_name(:updated_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.id, project_path(project) %></td>
        <td><%= link_to project.title, project_path(project) %></td>
        <td><%= project.user.name %></td>
        <td><%= project.start_date %></td>
        <td><%= project.end_date %></td>
        <td><%= project.updated_at.localtime %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_project_path(project), :class => 'btn btn-mini' if current_user == project.user %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      project_path(project),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' if current_user == project.user%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_project_path,
            :class => 'btn btn-primary' %>

app/views/projects/new.html.erb
<%- model_class = @project.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/projects/show.html.erb
<%- model_class = @project.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %> "<%= @project.title %>"</h1>

<p>
  <strong><%= model_class.human_attribute_name(:description) %>:</strong>
  <%= simple_format(@project.description) %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:owner) %>:</strong>
  <%= @project.user.name %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:start_date) %>:</strong>
  <%= @project.start_date %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:end_date) %>:</strong>
  <%= @project.end_date %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:max_attends_number) %>:</strong>
  <%= @project.max_attends_number %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:point) %>:</strong>
  <%= @project.point %>
</p>

<p>
	<strong><%= model_class.human_attribute_name(:surveys) %>:</strong><br/>
	<% @surveys.each do |survey| %>
	  <li><%=link_to survey.title, project_survey_path(@project, survey) %></li>
	<% end %>
</p>


<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              projects_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_project_path(@project), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              project_path(@project),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
	<%= link_to '설문지 추가', new_project_survey_path(@project), :class => 'btn' %>
</div>

<% @members.each do |member| %>
<%= member.user.id %> 
<%= member.user.name %> 
<%= member.user.email %>
[<%= member.workflow_state %>]
<% if member.workflow_state != 'accepted' %>
	<%= link_to '승인', {:controller => 'join_projects', :action => 'event', :id => member, :event => 'accept'}, :remote => true, :method => :put %>
<% end %>
<% if member.workflow_state == 'accepted' %>
	<%= link_to '거절', {:controller => 'join_projects', :action => 'event', :id => member, :event => 'reject'}, :remote => true, :method => :put %>

	<%= link_to '스캐줄초기화', {:controller => 'join_projects', :action => 'event', :id => member, :event => 'reset_schedule'}, :remote => true, :method => :put %>
<% end %>

<br/>
<% end %>