config/routes.rb
EsmRails::Application.routes.draw do
  
  resources :directories

  resources :posts do
    collection do
      put :update_attribute_on_the_spot
    end
  end

  devise_for :admins

  root :to => "projects#index"

  devise_for :users, :controllers => {sessions: "sessions"}
  resources :users, :only => :show

  resources :users do
    resources :projects
  end

  resources :projects do
    resources :surveys do
      resources :survey_schedules, :only => :index
    end
    get 'mine', :on => :collection
  end
  
  resources :surveys do
    resources :questions
  end
  
  resources :questions do
    resources :examples
  end
  
  resources :examples
  
  resources :answers

  resources :take_surveys do
    member do
      put 'event'
    end
  end
  
  resources :join_projects do
    member do
      put 'event'
    end
  end
  
  resources :user_histories do
    get 'mine', :on => :collection
  end

  resources :device_tokens, :only => [:create, :destroy]
  
  match 'survey_reports/:id' => 'survey_report#show'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :trackable, :timeoutable, :lockable
  attr_accessible :email, :password, :password_confirmation
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :take_survey
  
  validates_uniqueness_of :take_survey_id, :scope => :question_id
end

app/models/device_token.rb
class DeviceToken < ActiveRecord::Base
  belongs_to :user
  
  validates_uniqueness_of :user_id, :scope => :token
end

app/models/directory.rb
class Directory < ActiveRecord::Base
  has_ancestry
end

app/models/example.rb
class Example < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
end

app/models/join_project.rb
class JoinProject < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  
  validates_uniqueness_of :user_id, :scope => :project_id
  
  include Workflow
  workflow do
    state :requested do
      event :cancel, :transitions_to => :canceled
      event :review, :transitions_to => :in_review
      event :accept, :transitions_to => :accepted
    end
    state :canceled do
      event :request, :transitions_to => :requested
    end
    state :in_review do
      event :accept, :transitions_to => :accepted
      event :reject, :transitions_to => :rejected
    end    
    state :accepted do
      event :reject, :transitions_to => :rejected
      event :abandon, :transitions_to => :abandoned
      event :finish, :transitions_to => :finished
      event :reset_schedule, :transitions_to => :accepted
    end
    state :rejected do
      event :accept, :transitions_to => :accepted
    end
    
    state :abandoned
    state :finished
  end
end

app/models/pns_log.rb
class PnsLog < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  belongs_to :survey
end

app/models/pns_rule.rb
class PnsRule < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :surveys
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :survey
  belongs_to :user
  has_many :examples
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  has_many :questions,:order => 'display_no ASC'
end

app/models/survey_schedule.rb
class SurveySchedule < ActiveRecord::Base
  belongs_to :user
  belongs_to :survey
end

app/models/take_survey.rb
class TakeSurvey < ActiveRecord::Base
  belongs_to :user
  belongs_to :survey
  belongs_to :survey_schedule
  
  # validates_uniqueness_of :user_id, :scope => :survey_id
  
  include Workflow
  workflow do
    state :before_taking do
      event :take, :transitions_to => :on_taking
    end
    state :on_taking do
      event :finish, :transitions_to => :done
      event :timeout, :transitions_to => :not_finish
    end
    state :complete
    state :incomplete
    state :not_finish
  end  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  before_save :ensure_authentication_token
    
  # Include default devise modules. Others available are:
  # :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :token_authenticatable

  # Setup accessible (or protected) attributes for your model
  # attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :authentication_token

  def ensure_authentication_token!   
     reset_authentication_token! if authentication_token.blank?   
  end
  
  def serializable_hash(options = {})
    # options[:except] ||= [:confirmation_token, :encrypted_password, :token_authenticatable]
    options[:only] ||= [:email, :name, :id, :created_at, :updated_at, :authentication_token]
    super(options)
  end
end

app/models/user_history.rb
class UserHistory < ActiveRecord::Base
  belongs_to :user
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  
  before_filter :authenticate_user!, :except => [:index, :show]
    
  def index
    @surveys = Survey.where('project_id = ?', params[:project_id])
    @project = Project.find(params[:project_id])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @surveys }
    end
  end
  
  def show
    @survey = Survey.find(params[:id])
    @project = @survey.project
    @questions = @survey.questions.order(:display_no)
    if stale? etag: [@survey, @project, @questions]
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @survey.to_json(:include => {:questions => 
          {:only => [:id, :title, :qtype, :type_param, :description], :include => {:examples => {:only => [:id, :title]}}}}) }
      end
    end    
  end
  
  def new
    @project = Project.find(params[:project_id])
    @survey = Survey.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @survey }
    end
  end
  
  def create
    project_id = params[:survey][:project_id]
    @project = Project.find(project_id)
    @survey = @project.surveys.create(params[:survey])
    
    respond_to do |format|
      if @survey.save
        format.html { redirect_to project_survey_path(@project, @survey), notice: 'Survey was successfully created.' }
        format.json { render json: @survey, status: :created, location: @survey }
      else
        format.html { render action: "new" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def edit
    @survey = Survey.find(params[:id])
    @project = @survey.project
  end
  
  def update
    @survey = Survey.find(params[:id])
    @project = @survey.project

    respond_to do |format|
      if @survey.update_attributes(params[:survey])
        format.html { redirect_to project_survey_path(@project, @survey), notice: 'Survey was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @survey = Survey.find(params[:id])
    @project = @survey.project
    
    if user_signed_in? and current_user == @project.user
      @survey.destroy

      respond_to do |format|
        format.html { redirect_to project_surveys_path(@project) }
        format.json { head :ok }
      end
    else
      respond_to do |format|
        format.html { head :forbidden }
        format.json { head :forbidden }
      end
    end
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/examples_helper.rb
module ExamplesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/surveys/_form.html.erb
<%= form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :project_id, :value => @project.id %>
  <%= f.hidden_field :user_id, :value => current_user.id %>

  <div class="field">
    <%= f.label "설문 제목" %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label "설문에 대한 간단한 요약" %><br />
    <%= f.text_area :description %>
  </div>

  <div class="field">
	  <%= f.label "몇 일간 설문" %><br />
	  <%= f.number_field :days %>
  </div>	  

  <div class="field">
	  <%= f.label "하루에 몇 번 설문" %><br />
	  <%= f.number_field :repeatTime %>
  </div>

  <div class="field">
	  <%= f.label "시작시간" %><br />
	  <%= f.text_field :begin_at %>
  </div>

  <div class="field">
	  <%= f.label "종료시간" %><br />
	  <%= f.text_field :end_at %>
  </div>

  <div class="field">
	  <%= f.label "회차간 최소 간격(분)" %><br />
	  <%= f.number_field :interval_min %>
  </div>

  <div class="field">
	  <%= f.label "회차간 최대 간격(분)" %><br />
	  <%= f.number_field :interval_max %>
  </div>

  <div class="actions">
	  <%= f.submit %>
  </div>
<% end %>

app/views/surveys/edit.html.erb
<h1>설문을 수정합니다</h1>

<%= render 'form' %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', project_surveys_path(@project) %>

app/views/surveys/index.html.erb
<h3>Surveys of "<%=link_to @project.title, @project%>"</h3>

	<% if @surveys.empty? %>
	  <p> 설문지가 없어요. <%=link_to '추가할까요?', new_project_survey_path(@project) %> </p>
	<% else %>
		<% @surveys.each do |survey| %>
		  <li><%=link_to survey.title, project_survey_path(@project, survey) %></li>
		<% end %>
		
		<br />
		<%= link_to '새 설문지', new_project_survey_path(@project) %>
	<% end %>

app/views/surveys/new.html.erb
<h1>새 설문을 작성합니다</h1>

<%= render 'form' %>

<%= link_to 'Back', project_surveys_path(@project) %>

app/views/surveys/show.html.erb
<h1><%= @survey.title %></h1>
<p>설문지 개요: <%= @survey.description if @survey.description %></p>
<p> <%= @survey.days if @survey.days %>일 동안, 매일 <%= @survey.repeatTime if @survey.repeatTime %>회 반복
<ol>	
<% @questions.each do |question| %>
  <li><%=link_to question.title, survey_question_path(@survey, question) %></li>
		<ol type='a'>
	<% question.examples.each do |example| %>
		<li><%=link_to example.title, question_example_path(question, example)%></li>
	<% end %>
		</ol>
<% end %>
</ol>

<% if user_signed_in? and current_user == @project.user %>
<%= link_to 'Edit', edit_project_survey_path(@project, @survey) %> |
<%= link_to 'Destroy', @survey, confirm: 'Are you sure?', method: :delete %> |
<%= link_to '문제추가', new_survey_question_path(@survey) %> |
<% end %>
<%= link_to 'Back', project_surveys_path(@project) %> 